version: '2.1'
services:
  web:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - .:/app
      - ./dev/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
      - db
  php:
    build: ./docker/php
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jscouch
      MYSQL_USER: jscouch
      MYSQL_PASSWORD: jscouch
  adminer:
    image: adminer
    ports:
      - 3001:8080
    links:
      - db
